FROM php:7.4-fpm

# Install the required PHP extensions
RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libzip-dev \
    zip \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install mysqli pdo pdo_mysql \
    && docker-php-ext-enable mysqli pdo pdo_mysql

# Copy any additional PHP configuration files if necessary
COPY php.ini /usr/local/etc/php/

# Copy application files (optional, if not using volumes)
# COPY . /var/www/html

WORKDIR /var/www/html
